concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  maven4:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Cache Maven 4 Build Cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-build-cache-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/build-cache
        restore-keys: '${{ runner.os }}-maven-build-cache

          '
    - continue-on-error: true
      name: Setup Temurin JDK 8, 11, 17 & 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8

          11

          17

          21

          '
    - continue-on-error: true
      name: Setup Maven 4
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: 4.0.0-alpha-10
    - continue-on-error: true
      name: Test
      run: mvn clean verify
name: Maven 4
on:
  repository_dispatch:
    types: trigger-ga___maven4.yml
