concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/ruby
jobs:
  arm64:
    name: Ruby on Linux ARM64
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache gems
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        path: .gem
        restore-keys: '${{ runner.os }}-gems-

          '
    - continue-on-error: true
      name: Install dependencies
      run: 'sudo apt-get update -q

        sudo apt-get install -q -y ruby-dev bundler libsnappy-dev libyaml-dev

        '
    - continue-on-error: true
      name: Build
      run: 'set -x

        ./build.sh clean test

        '
name: Test Ruby on ARM
on:
  repository_dispatch:
    types: trigger-ga___test-lang-ruby-ARM.yml
