concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/csharp
jobs:
  arm64:
    name: C# on Linux ARM64
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Nuget
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        path: ~/.nuget/packages
        restore-keys: '${{ runner.os }}-nuget-

          '
    - continue-on-error: true
      name: Install dependencies
      run: 'sudo apt-get update -q

        sudo apt-get install -q -y wget libzstd-dev libicu-dev

        wget https://dot.net/v1/dotnet-install.sh

        bash ./dotnet-install.sh --channel "3.1" --install-dir "$HOME/.dotnet" # 3.1

        bash ./dotnet-install.sh --channel "5.0" --install-dir "$HOME/.dotnet" # 5.0

        bash ./dotnet-install.sh --channel "6.0" --install-dir "$HOME/.dotnet" # 6.0

        bash ./dotnet-install.sh --channel "7.0" --install-dir "$HOME/.dotnet" # 7.0

        bash ./dotnet-install.sh --channel "8.0" --install-dir "$HOME/.dotnet" # 8.0

        '
    - continue-on-error: true
      name: Build
      run: 'set -x

        export PATH=$HOME/.dotnet:$PATH

        dotnet --list-sdks

        ./build.sh clean test

        '
  interop:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Add libzstd
      run: sudo apt-get install -y libzstd-dev
      shell: bash
    - continue-on-error: true
      name: Install .NET SDKs
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x

          5.0.x

          6.0.x

          7.0.x

          8.0.x

          '
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Temurin JDK 8, 11, 17 & 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8

          11

          17

          21

          '
    - continue-on-error: true
      name: Setup Maven 3.9.6
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      name: Install Java Avro for Interop Test
      run: mvn -B install -PskipQuality
      working-directory: .
    - continue-on-error: true
      name: Create Interop Data Directory
      run: mkdir -p build/interop/data
      working-directory: .
    - continue-on-error: true
      name: Generate Interop Resources
      run: mvn -B -P interop-data-generate generate-resources
      working-directory: lang/java/avro
    - continue-on-error: true
      name: Generate Interop Data
      run: ./build.sh interop-data-generate
    - continue-on-error: true
      name: Run Interop Tests
      run: ./build.sh interop-data-test
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Add libzstd
      run: sudo apt-get install -y libzstd-dev
      shell: bash
    - continue-on-error: true
      name: Install .NET SDKs
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x

          5.0.x

          6.0.x

          7.0.x

          8.0.x

          '
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        path: ~/.nuget/packages
        restore-keys: '${{ runner.os }}-nuget-

          '
    - continue-on-error: true
      name: Lint
      run: ./build.sh lint
    - continue-on-error: true
      name: Test
      run: ./build.sh test
name: Test C# on ARM
on:
  repository_dispatch:
    types: trigger-ga___test-lang-csharp-ARM.yml
