concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/php
jobs:
  interop:
    name: PHP ${{ matrix.php }} Interop
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:2.2.5
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Temurin JDK 8, 11, 17 & 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8

          11

          17

          21

          '
    - continue-on-error: true
      name: Setup Maven 3.9.6
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      name: Install Java Avro for Interop Test
      run: mvn -B install -PskipQuality
      working-directory: .
    - continue-on-error: true
      name: Create Interop Data Directory
      run: mkdir -p build/interop/data
      working-directory: .
    - continue-on-error: true
      name: Generate Interop Resources
      run: mvn -B -P interop-data-generate generate-resources
      working-directory: lang/java/avro
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        path: lang/php/php-ext-zstd
        repository: kjdev/php-ext-zstd
    - continue-on-error: true
      name: Install php-ext-zstd
      run: 'sudo apt-get install -qqy --no-install-recommends libzstd-dev libbz2-dev

        phpize

        ./configure --with-libzstd

        make

        sudo make install

        echo "extension=zstd.so" | sudo tee -a /etc/php/${{ matrix.php }}/cli/conf.d/10-zstd.ini

        php -m

        '
      working-directory: lang/php/php-ext-zstd
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        path: lang/php/php-ext-snappy
        repository: kjdev/php-ext-snappy
        submodules: true
    - continue-on-error: true
      name: Install php-ext-snappy
      run: 'sudo apt-get install -qqy --no-install-recommends libsnappy-dev

        phpize

        ./configure --with-libsnappy

        make

        sudo make install

        echo "extension=snappy.so" | sudo tee -a /etc/php/${{ matrix.php }}/cli/conf.d/10-snappy.ini

        php -m

        '
      working-directory: lang/php/php-ext-snappy
    - continue-on-error: true
      name: Generate Interop Data
      run: ./build.sh interop-data-generate
    - continue-on-error: true
      name: Run Interop Tests
      run: ./build.sh test-interop
    strategy:
      matrix:
        php:
        - '7.3'
        - '7.4'
        - '8.0'
  test:
    name: PHP ${{ matrix.php }} Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:2.2.5
    - continue-on-error: true
      id: composer-cache
      name: Get Composer Cache Directory
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        path: ${{ steps.composer-cache.outputs.dir }}
        restore-keys: '${{ runner.os }}-composer-

          '
    - continue-on-error: true
      name: Lint
      run: ./build.sh lint
    - continue-on-error: true
      name: Test
      run: ./build.sh test
    strategy:
      matrix:
        php:
        - '7.3'
        - '7.4'
        - '8.0'
name: Test PHP
on:
  repository_dispatch:
    types: trigger-ga___test-lang-php.yml
