concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/c
jobs:
  interop:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install Dependencies
      run: "sudo apt-get install -qqy --no-install-recommends libbz2-dev \\\n    \
        \                                              libjansson-dev \\\n       \
        \                                           liblzma-dev \\\n             \
        \                                     libsnappy-dev \\\n                 \
        \                                 libzstd-dev\n"
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Temurin JDK 8, 11, 17 & 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8

          11

          17

          21

          '
    - continue-on-error: true
      name: Setup Maven 3.9.6
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      name: Install Java Avro for Interop Test
      run: mvn -B install -PskipQuality
      working-directory: .
    - continue-on-error: true
      name: Create Interop Data Directory
      run: mkdir -p build/interop/data
      working-directory: .
    - continue-on-error: true
      name: Generate Interop Resources
      run: mvn -B -P interop-data-generate generate-resources
      working-directory: lang/java/avro
    - continue-on-error: true
      name: Generate Interop Data
      run: ./build.sh interop-data-generate
    - continue-on-error: true
      name: Run Interop Tests
      run: ./build.sh interop-data-test
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install Dependencies
      run: sudo apt-get install -qqy libjansson-dev libsnappy-dev
    - continue-on-error: true
      name: Lint
      run: ./build.sh lint
    - continue-on-error: true
      name: Test
      run: ./build.sh test
    - continue-on-error: true
      name: Check pkg-config
      run: 'mkdir -p build

        cd build

        cmake ..

        export PKG_CONFIG_PATH=./src

        pkg-config --libs avro-c

        '
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Temurin JDK 8, 11, 17 & 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8

          11

          17

          21

          '
    - continue-on-error: true
      name: Setup Maven 3.9.6
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      name: Install Java Avro for Interop Test
      run: mvn -B install -PskipQuality
      working-directory: .
    - continue-on-error: true
      name: Create Interop Data Directory
      run: mkdir -p build/interop/data
      working-directory: .
    - continue-on-error: true
      name: Generate Interop Resources
      run: mvn -B -P interop-data-generate generate-resources
      working-directory: lang/java/avro
    - continue-on-error: true
      name: Generate Interop Data
      run: ./build.sh interop-data-generate
    - continue-on-error: true
      name: Run Interop Tests
      run: ./build.sh interop-data-test
name: Test C
on:
  repository_dispatch:
    types: trigger-ga___test-lang-c.yml
