concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/ruby
jobs:
  interop:
    name: Ruby ${{ matrix.ruby }} Interop
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - continue-on-error: true
      name: Install Dependencies
      run: sudo apt-get install -qqy libsnappy-dev
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        path: .gem
        restore-keys: '${{ runner.os }}-gems-

          '
    - continue-on-error: true
      name: Configure Bundler to Use Cache
      run: bundle config path .gem
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Temurin JDK 8, 11, 17 & 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8

          11

          17

          21

          '
    - continue-on-error: true
      name: Setup Maven 3.9.6
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      name: Install Java Avro for Interop Test
      run: mvn -B install -PskipQuality
      working-directory: .
    - continue-on-error: true
      name: Create Interop Data Directory
      run: mkdir -p build/interop/data
      working-directory: .
    - continue-on-error: true
      name: Generate Interop Resources
      run: mvn -B -P interop-data-generate generate-resources
      working-directory: lang/java/avro
    - continue-on-error: true
      name: Bundle Install
      run: 'export GEM_HOME="$PWD/.gem/"

        export PATH="$GEM_HOME/bin:$PATH"

        bundle install

        '
    - continue-on-error: true
      name: Generate Interop Data
      run: 'export GEM_HOME="$PWD/.gem/"

        export PATH="$GEM_HOME/bin:$PATH"

        bundle exec rake --trace generate_interop

        '
    - continue-on-error: true
      name: Run Interop Tests
      run: 'export GEM_HOME="$PWD/.gem/"

        export PATH="$GEM_HOME/bin:$PATH"

        bundle exec rake --trace interop

        '
    strategy:
      matrix:
        ruby:
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
  test:
    name: Ruby ${{ matrix.ruby }} Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - continue-on-error: true
      name: Install Dependencies
      run: sudo apt-get install -qqy libsnappy-dev
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        path: .gem
        restore-keys: '${{ runner.os }}-gems-

          '
    - continue-on-error: true
      name: Configure Bundler to Use Cache
      run: bundle config path .gem
    - continue-on-error: true
      name: Lint
      run: 'PATH=$PWD/.gem/bin:$PATH

        ./build.sh lint

        '
    - continue-on-error: true
      name: Test
      run: 'PATH=$PWD/.gem/bin:$PATH

        ./build.sh test

        '
    strategy:
      matrix:
        ruby:
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
name: Test Ruby
on:
  repository_dispatch:
    types: trigger-ga___test-lang-ruby.yml
