concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/java
jobs:
  arm64:
    name: Java on Linux ARM64
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sourcecode
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Setup Temurin JDK 8, 11, 17 & 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8

          11

          17

          21

          '
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Maven 3.9.6
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      name: Build
      run: ./build.sh clean test
name: Test Java on ARM
on:
  repository_dispatch:
    types: trigger-ga___test-lang-java-ARM.yml
