concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/rust
env:
  RUSTFLAGS: -Dwarnings
jobs:
  clippy_check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy
        toolchain: ${{ matrix.rust }}
    - continue-on-error: true
      run: cargo clippy --all-features --all-targets -- -Dclippy::all -Dunused_imports
    strategy:
      matrix:
        rust:
        - stable
        - 1.70.0
name: Rust Clippy Check
on:
  repository_dispatch:
    types: trigger-ga___test-lang-rust-clippy.yml
permissions:
  contents: read
