concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/js
jobs:
  interop:
    name: Node ${{ matrix.node }} Interop
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-node-

          '
    - continue-on-error: true
      name: Setup Python for Generating Input Data
      uses: actions/setup-python@v5
    - continue-on-error: true
      name: Apt Install Compression Libs Required by Python
      run: "sudo apt-get install -qqy --no-install-recommends libbz2-dev \\\n    \
        \                                              liblzma-dev \\\n          \
        \                                        libsnappy-dev \\\n              \
        \                                    libzstd-dev\n"
    - continue-on-error: true
      name: Install Python Dependencies
      run: 'python3 -m pip install --upgrade pip setuptools tox

        python3 -m pip install python-snappy zstandard

        '
    - continue-on-error: true
      name: Create Interop Data Directory
      run: mkdir -p build/interop/data
      working-directory: .
    - continue-on-error: true
      name: Generate Interop Data using Python
      run: ./build.sh interop-data-generate
      working-directory: lang/py
    - continue-on-error: true
      name: Generate Interop Data
      run: ./build.sh interop-data-generate
    - continue-on-error: true
      name: Run Interop Tests
      run: npm install && ./build.sh interop-data-test
    strategy:
      matrix:
        node:
        - 12
        - 14
        - 16
  test:
    name: Node ${{ matrix.node }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-node-

          '
    - continue-on-error: true
      name: Lint
      run: ./build.sh lint
    - continue-on-error: true
      name: Test
      run: ./build.sh test
    strategy:
      matrix:
        node:
        - 12
        - 14
        - 16
name: Test JavaScript
on:
  repository_dispatch:
    types: trigger-ga___test-lang-js.yml
