concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/py
jobs:
  arm64:
    name: Python on Linux ARM64
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install dependencies
      run: 'sudo apt-get update -q

        sudo apt-get install -q -y python3 python3-dev python3-pip git libbz2-dev
        libjansson-dev liblzma-dev libsnappy-dev libzstd-dev

        python3 -m pip install --upgrade pip setuptools tox

        '
    - continue-on-error: true
      name: Build
      run: 'set -x

        ./build.sh clean test

        '
name: Test Python on ARM
on:
  repository_dispatch:
    types: trigger-ga___test-lang-py-ARM.yml
