concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/c++
jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install Dependencies
      run: sudo apt update && sudo apt-get install -qqy cppcheck libboost-all-dev
        libsnappy-dev libfmt-dev cmake
    - continue-on-error: true
      name: Clean
      run: ./build.sh clean
    - continue-on-error: true
      name: Lint
      run: ./build.sh lint
    - continue-on-error: true
      name: Test
      run: ./build.sh test
    - continue-on-error: true
      name: Release build
      run: 'mkdir -p build

        cd build

        cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release ..

        '
name: Test C++
on:
  repository_dispatch:
    types: trigger-ga___test-lang-c++.yml
