concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/rust
env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git
  RUSTFLAGS: -Dwarnings
jobs:
  arm64:
    name: Rust on Linux ARM64
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Cargo
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-target-arm64-${{ hashFiles('**/Cargo.lock') }}
        path: ~/.cargo
    - continue-on-error: true
      name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-target-cache1-stable-
        path: lang/rust/target
    - continue-on-error: true
      name: Rust Toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
        targets: x86_64-unknown-linux-gnu
        toolchain: stable
    - continue-on-error: true
      name: Build
      run: 'set -x

        ./build.sh test

        '
name: Rust Continuous Integration on ARM
on:
  repository_dispatch:
    types: trigger-ga___test-lang-rust-ci-ARM.yml
permissions:
  contents: read
