concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/java
jobs:
  interop:
    name: Java Interop
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Temurin JDK 11, 17 & 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '11

          17

          21

          '
    - continue-on-error: true
      name: Setup Maven 3.9.6
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      name: Setup Python for Generating Input Data
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
    - continue-on-error: true
      name: Apt Install Compression Libs Required by Python
      run: "sudo apt-get install -qqy --no-install-recommends libbz2-dev \\\n    \
        \                                              liblzma-dev \\\n          \
        \                                        libsnappy-dev \\\n              \
        \                                    libzstd-dev\n"
    - continue-on-error: true
      name: Install Python Dependencies
      run: 'python3 -m pip install --upgrade pip setuptools tox

        python3 -m pip install python-snappy zstandard

        '
    - continue-on-error: true
      name: Setup C# for Generating Interop Data
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x

          5.0.x

          6.0.x

          7.0.x

          8.0.x

          '
    - continue-on-error: true
      name: Create Interop Data Directory
      run: mkdir -p build/interop/data
      working-directory: .
    - continue-on-error: true
      name: Generate Interop Data using Python
      run: ./build.sh interop-data-generate
      working-directory: lang/py
    - continue-on-error: true
      name: Generate Interop Data using C#
      run: ./build.sh interop-data-generate
      working-directory: lang/csharp
    - continue-on-error: true
      name: Install Java Avro for other tests
      run: mvn -B install -PskipQuality
      working-directory: .
    - continue-on-error: true
      name: Generate Interop Data using Java 11, 17 & 21
      run: mvn -B verify -Pgenerate-test-data
      working-directory: lang/java/interop-data-test
    - continue-on-error: true
      name: Run Interop Tests using Java 11, 17 & 21
      run: mvn -B verify -Pcheck-test-data
      working-directory: lang/java/interop-data-test
  test:
    name: Java Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sourcecode
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Temurin JDK 11, 17 & 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '11

          17

          21

          '
    - continue-on-error: true
      name: Setup Maven 3.9.6
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      name: Java Lint
      run: ./build.sh lint
    - continue-on-error: true
      name: Java Test
      run: ./build.sh test
    - continue-on-error: true
      name: Install Java Avro for reproducibility test
      run: mvn -B clean install -PskipQuality
      working-directory: .
    - continue-on-error: true
      name: Test Reproducible Build
      run: mvn clean verify -PskipQuality artifact:compare
      working-directory: .
name: Test Java
on:
  repository_dispatch:
    types: trigger-ga___test-lang-java.yml
