concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    working-directory: lang/perl
jobs:
  interop:
    name: Perl ${{ matrix.perl }} Interop
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
    - continue-on-error: true
      name: Install Dependencies
      run: "sudo apt-get -qqy install --no-install-recommends libcompress-raw-zlib-perl\
        \ \\\n                                                  libcpan-uploader-perl\
        \ \\\n                                                  libencode-perl \\\n\
        \                                                  libio-string-perl \\\n\
        \                                                  libjansson-dev \\\n   \
        \                                               libjson-xs-perl \\\n     \
        \                                             libmodule-install-perl \\\n\
        \                                                  libmodule-install-readmefrompod-perl\
        \ \\\n                                                  libobject-tiny-perl\
        \ \\\n                                                  libsnappy-dev \\\n\
        \                                                  libtest-exception-perl\
        \ \\\n                                                  libtest-pod-perl\n\
        cpanm --mirror https://www.cpan.org/ install Compress::Zstd \\\n         \
        \                                    Error::Simple \\\n                  \
        \                           Module::Install::Repository \\\n             \
        \                                Object::Tiny \\\n                       \
        \                      Regexp::Common \\\n                               \
        \              Try::Tiny \\\n                                            \
        \ inc::Module::Install\n"
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Temurin JDK 8, 11, 17 & 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8

          11

          17

          21

          '
    - continue-on-error: true
      name: Setup Maven 3.9.6
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      name: Install Java Avro for Interop Test
      run: mvn -B install -PskipQuality
      working-directory: .
    - continue-on-error: true
      name: Create Interop Data Directory
      run: mkdir -p build/interop/data
      working-directory: .
    - continue-on-error: true
      name: Generate Interop Resources
      run: mvn -B -P interop-data-generate generate-resources
      working-directory: lang/java/avro
    - continue-on-error: true
      name: Generate Interop Data
      run: ./build.sh interop-data-generate
    - continue-on-error: true
      name: Run Interop Tests
      run: ./build.sh interop-data-test
    strategy:
      matrix:
        perl:
        - '5.32'
  test:
    name: Perl ${{ matrix.perl }} Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
    - continue-on-error: true
      name: Install Dependencies
      run: "sudo apt-get -qqy install --no-install-recommends libjansson-dev \\\n\
        \                                                  libcompress-raw-zlib-perl\
        \ \\\n                                                  libcpan-uploader-perl\
        \ \\\n                                                  libencode-perl \\\n\
        \                                                  libio-string-perl \\\n\
        \                                                  libjson-xs-perl \\\n  \
        \                                                libmodule-install-perl \\\
        \n                                                  libmodule-install-readmefrompod-perl\
        \ \\\n                                                  libobject-tiny-perl\
        \ \\\n                                                  libperl-critic-perl\
        \ \\\n                                                  libsnappy-dev \\\n\
        \                                                  libtest-exception-perl\
        \ \\\n                                                  libtest-pod-perl\n\
        cpanm --mirror https://www.cpan.org/ install Compress::Zstd \\\n         \
        \                                    Error::Simple \\\n                  \
        \                           Module::Install::Repository \\\n             \
        \                                Regexp::Common \\\n                     \
        \                        Try::Tiny \\\n                                  \
        \           inc::Module::Install \\\n                                    \
        \         Module::Install::ReadmeFromPod \\\n                            \
        \                 Test::Exception \\\n                                   \
        \          IO::String \\\n                                             Object::Tiny\n"
    - continue-on-error: true
      name: Lint
      run: ./build.sh lint
    - continue-on-error: true
      name: Test
      run: ./build.sh test
    strategy:
      matrix:
        perl:
        - '5.32'
name: Test Perl
on:
  repository_dispatch:
    types: trigger-ga___test-lang-perl.yml
